#ifndef __DESCRIPTION_HPP__
#define __DESCRIPTION_HPP__

#include <string>
#include <vector>

namespace ros2_control_test_assets
{

const auto omni_wheel_robot_urdf =
  R"(
<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from sample_robot.urdf.xacro        | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="sample_robot">
  <material name="gray">
    <color rgba="0.8 0.8 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="1.0 0 0 1.0"/>
  </material>
  <material name="light_red">
    <color rgba="1.0 0.5 0.5 1.0"/>
  </material>
  <material name="yellow">
    <color rgba="0 1.0 1.0 1.0"/>
  </material>
  <!-- =============== Link & Joint =============== -->
  <!-- Base -->
  <link name="base_link"/>
  <joint name="base_frame_link_joint" type="fixed">
    <origin xyz="0 0 0.06"/>
    <parent link="base_link"/>
    <child link="base_frame_link"/>
  </joint>
  <link name="base_frame_link">
    <visual>
      <geometry>
        <box size="0.6 0.6 0.02"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.6 0.6 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="20.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>
  <joint name="wheel0_shaft_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel0_housing_link"/>
    <origin rpy="0 1.5707963267948966 0.7853981633974483" xyz="0.35 0.35 0.05"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  <transmission name="wheel0_shaft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel0_shaft_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel0_shaft_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="wheel0_housing_link">
    <visual>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </collision>
    <inertial>
      <mass value="1.288"/>
      <inertia ixx="0.00235" ixy="0" ixz="0" iyy="0.00235" iyz="0" izz="0.00004"/>
    </inertial>
  </link>
  <gazebo reference="wheel0_housing_link">
    <material>Gazebo/Gray</material>
    <mu1>0.8</mu1>
    <mu2>0.05</mu2>
    <fdir1>0 1.0 0</fdir1>
    <kp value="30000000.0"/>
    <kd value="50000000.0"/>
  </gazebo>
  <joint name="wheel1_shaft_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel1_housing_link"/>
    <origin rpy="0 1.5707963267948966 2.356194490192345" xyz="-0.35 0.35 0.05"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  <transmission name="wheel1_shaft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel1_shaft_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel1_shaft_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="wheel1_housing_link">
    <visual>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </collision>
    <inertial>
      <mass value="1.288"/>
      <inertia ixx="0.00235" ixy="0" ixz="0" iyy="0.00235" iyz="0" izz="0.00004"/>
    </inertial>
  </link>
  <gazebo reference="wheel1_housing_link">
    <material>Gazebo/Gray</material>
    <mu1>0.8</mu1>
    <mu2>0.05</mu2>
    <fdir1>0 1.0 0</fdir1>
    <kp value="30000000.0"/>
    <kd value="50000000.0"/>
  </gazebo>
  <joint name="wheel2_shaft_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel2_housing_link"/>
    <origin rpy="0 1.5707963267948966 -2.356194490192345" xyz="-0.35 -0.35 0.05"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  <transmission name="wheel2_shaft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel2_shaft_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel2_shaft_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="wheel2_housing_link">
    <visual>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </collision>
    <inertial>
      <mass value="1.288"/>
      <inertia ixx="0.00235" ixy="0" ixz="0" iyy="0.00235" iyz="0" izz="0.00004"/>
    </inertial>
  </link>
  <gazebo reference="wheel2_housing_link">
    <material>Gazebo/Gray</material>
    <mu1>0.8</mu1>
    <mu2>0.05</mu2>
    <fdir1>0 1.0 0</fdir1>
    <kp value="30000000.0"/>
    <kd value="50000000.0"/>
  </gazebo>
  <joint name="wheel3_shaft_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel3_housing_link"/>
    <origin rpy="0 1.5707963267948966 -0.7853981633974483" xyz="0.35 -0.35 0.05"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>
  <transmission name="wheel3_shaft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel3_shaft_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel3_shaft_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="wheel3_housing_link">
    <visual>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.040" radius="0.05"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray"/>
    </collision>
    <inertial>
      <mass value="1.288"/>
      <inertia ixx="0.00235" ixy="0" ixz="0" iyy="0.00235" iyz="0" izz="0.00004"/>
    </inertial>
  </link>
  <gazebo reference="wheel3_housing_link">
    <material>Gazebo/Gray</material>
    <mu1>0.8</mu1>
    <mu2>0.05</mu2>
    <fdir1>0 1.0 0</fdir1>
    <kp value="30000000.0"/>
    <kd value="50000000.0"/>
  </gazebo>
  <gazebo reference="base_link">
    <selfCollide>false</selfCollide>
    <mu1 value="0.05"/>
    <mu2 value="0.05"/>
  </gazebo>
  <ros2_control name="TestActuatorHardwareWheel0" type="actuator">
    <hardware>
      <plugin>test_actuator</plugin>
    </hardware>
    <joint name="wheel0_shaft_joint">
      <state_interface name="position"/>
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
  <ros2_control name="TestActuatorHardwareWheel1" type="actuator">
    <hardware>
      <plugin>test_actuator</plugin>
    </hardware>
    <joint name="wheel1_shaft_joint">
      <state_interface name="position"/>
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
  <ros2_control name="TestActuatorHardwareWheel2" type="actuator">
    <hardware>
      <plugin>test_actuator</plugin>
    </hardware>
    <joint name="wheel2_shaft_joint">
      <state_interface name="position"/>
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
  <ros2_control name="TestActuatorHardwareWheel3" type="actuator">
    <hardware>
      <plugin>test_actuator</plugin>
    </hardware>
    <joint name="wheel3_shaft_joint">
      <state_interface name="position"/>
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
</robot>
)";

}

#endif
